[package]
name = "binaryen_rs"
version = "0.1.0"
authors = ["Rusty Shackleford <a@neb.best>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[build-dependencies]
bindgen = "0.53.1"
inline-python = "0.6.0"