[package]
name = "kitchen-sink"
version = "0.1.0"
authors = ["Rusty Shackleford <a@neb.best>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binaryen_rs = {path = "../binaryen_rs"}
lazy_static = "1.4.0"